export const FETCH_CARD_TYPE_BY_ID = Symbol('FETCH_CARD_TYPE_BY_ID');
export const SET_EDIT_MODE = Symbol('SET_EDIT_MODE');
export const FETCH_PARTNER_TYPES = Symbol('FETCH_PARTNER_TYPES');
export const FETCH_OWNERSHIP_TYPES = Symbol('FETCH_OWNERSHIP_TYPES');
export const FETCH_CARD_BRANDS = Symbol('FETCH_CARD_BRANDS');
export const FETCH_CARD_NUMBER_CONSTRUCTION = Symbol('FETCH_CARD_NUMBER_CONSTRUCTION');
export const FETCH_BIN_TYPES = Symbol('FETCH_BIN_TYPES');
export const FETCH_CDOL1_PROFILES = Symbol('FETCH_CDOL1_PROFILES');
// export const FETCH_BUSINESS_UNITS = Symbol('FETCH_BUSINESS_UNITS');
export const FETCH_CIPHER = Symbol('FETCH_CIPHER');
export const FETCH_EMV_TAGS = Symbol('FETCH_EMV_TAGS');

export const UPDATE_SINGLE_VALUE = Symbol('UPDATE_SINGLE_VALUE');
export const UPDATE_GENERATE_CONTROL_DIGIT = Symbol('UPDATE_GENERATE_CONTROL_DIGIT');
export const UPDATE_MULTI_VALUE = Symbol('UPDATE_MULTI_VALUE');
export const SET_ERRORS = Symbol('SET_ERRORS');

export const CREATE_TYPE = Symbol('CREATE_TYPE');
export const RESET_STATE = Symbol('RESET_STATE');
export const TOGGLE_CREATE_CARD_TYPE_POPUP = Symbol('TOGGLE_CREATE_CARD_TYPE_POPUP');
