module.exports = {
    // application
    'application.add': require('./application/createName'), // TODO: fox this when there are 2 separate procedures for create
    'noNameApplication.add': require('./application/createNoName'),
    'application.fetch': require('./application/fetch'),
    'application.get': require('./application/get'),
    'issueType.fetch': require('./application/issueTypes'),
    'application.statusUpdate': require('./application/statusUpdate'),
    'customer.search': require('./application/customerSearch'),
    'customer.searchTSS': require('./application/customerSearchTSS'),
    'person.search': require('./application/personSearch'),
    'person.searchTSS': require('./application/personSearchTSS'),
    'account.search': require('./application/accountsSearch'),
    'account.searchTSS': require('./application/accountsSearchTSS'),
    // account
    'account.fetch': require('./account/fetch'),
    'queueOut.fetch': require('./queueOut/fetch'),
    'account.delete': require('./account/delete'),
    'account.setDefault': require('./account/setDefault'),
    'account.add': require('./account/add'),
    'accountType.list': require('./lists/list'),
    'customerType.list': require('./lists/list'),
    // batch
    'batch.fetch': require('./batch/fetch'),
    'batch.list': require('./batch/list'),
    'batch.get': require('./batch/get'),
    'batch.statusUpdate': require('./batch/statusUpdate'),
    'batch.addNoNameBatch': require('./batch/addNoNameBatch'),
    'batch.pansGet': require('./batch/pansGet'),
    'batch.checkDownload': require('./batch/checkDownload'),
    // card
    'cardInProduction.fetch': require('./card/fetch'),
    'cardInProduction.get': require('./card/get'),
    'card.search': require('./card/search'),
    'card.panGet': require('./card/panGet'),
    'card.statusUpdate': require('./card/statusUpdate'),
    // config
    'config.fetch': require('./config/fetch'),
    // cardInUse
    'cardInUse.fetch': require('./cardInUse/fetch'),
    'cardInUse.get': require('./cardInUse/get'),
    'cardInUse.statusUpdate': require('./cardInUse/statusUpdate'),
    // type
    'brand.fetch': require('./brand/fetch'),
    'embossedType.fetch': require('./lists/embossedType'),
    'ownershipType.fetch': require('./lists/ownershipType'),
    // product
    'product.list': require('./product/list'),
    'product.edit': require('./product/edit'),
    'product.add': require('./product/add'),
    'product.fetch': require('./product/fetch'),
    'product.get': require('./product/get'),
    'product.statusUpdate': require('./product/statusUpdate'),
    // type
    'type.list': require('./type/list'),
    'type.edit': require('./type/edit'),
    'type.add': require('./type/add'),
    'type.fetch': require('./type/fetch'),
    'type.get': require('./type/get'),
    'type.statusUpdate': require('./type/statusUpdate'),
    // reason
    'reason.fetch': require('./reason/fetch'),
    'reason.get': require('./reason/get'),
    'reason.add': require('./reason/add'),
    'reason.edit': require('./reason/edit'),
    'reason.delete': require('./reason/delete'),
    'reason.statusUpdate': require('./reason/statusUpdate'),
    // cardNumberConstruction
    'cardNumberConstruction.fetch': require('./cardNumberConstruction/fetch'),
    // bin
    'bin.add': require('./bin/add'),
    'bin.get': require('./bin/get'),
    'bin.edit': require('./bin/edit'),
    'bin.statusUpdate': require('./bin/statusUpdate'),
    'bin.fetch': require('./bin/fetch'),
    'bin.list': require('./bin/list'),
    // periodicCardFee
    'periodicCardFee.fetch': require('./periodicCardFee/fetch'),
    'batch.download': require('./batch/download'),
    // document
    'documentType.list': require('./document/list'),
    // reports
    'report.listOfCards': require('./report/listOfCards'),
    'report.queueOutFetch': require('./report/queueOutFetch'),
    // status
    'status.list': require('./status/list'),
    // actions
    'moduleAction.list': require('./action/list'),
    'cipher.list': require('./cipher/list'),
    'emvTags.list': require('./emvTags/list'),
    'cdol1Profile.list': require('./cdol1Profile/list'),
    'pinMailerFile.add': require('./pinMailerFile/add'),
    'pinMailerFile.fetch': require('./pinMailerFile/fetch')
};
