 DECLARE @cardActionCategoryId INT = (SELECT actionCategoryId FROM [user].[actionCategory] WHERE name = 'card')

if @cardActionCategoryId is null
begin
    insert into [user].[actionCategory](name)
    values ('card')

    set @cardActionCategoryId = SCOPE_IDENTITY()
end

declare @action [user].[actionTT]

insert into @action ([actionId], [actionCategoryId], [description], [valueMap])

VALUES ('card.account.search', @cardActionCategoryId, 'card.account.search', '{}')
    ,('card.account.searchTSS', @cardActionCategoryId, 'card.account.searchTSS', '{}')
    ,('card.account.searchCustom', @cardActionCategoryId, 'card.account.searchCustom', '{}')
    ,('card.accountType.list', @cardActionCategoryId, 'card.accountType.list', '{}')
    ,('card.application.add', @cardActionCategoryId, 'card.application.add', '{}')
    ,('card.application.fetch', @cardActionCategoryId, 'card.application.fetch', '{}')
    ,('card.application.get', @cardActionCategoryId, 'card.application.get', '{}')
    ,('card.application.statusUpdate', @cardActionCategoryId, 'card.application.statusUpdate', '{}')
    ,('card.application.statusUpdateAddToBatch', @cardActionCategoryId, 'card.application.statusUpdateAddToBatch', '{}')
    ,('card.application.statusUpdateApproveName', @cardActionCategoryId, 'card.application.statusUpdateApproveName', '{}')
    ,('card.application.statusUpdateApproveNoName', @cardActionCategoryId, 'card.application.statusUpdateApproveNoName', '{}')
    ,('card.application.statusUpdateCreateBatch', @cardActionCategoryId, 'card.application.statusUpdateCreateBatch', '{}')
    ,('card.application.statusUpdateEdit', @cardActionCategoryId, 'card.application.statusUpdateEdit', '{}')
    ,('card.application.statusUpdateRemoveFromBatch', @cardActionCategoryId, 'card.application.statusUpdateRemoveFromBatch', '{}')
    ,('card.application.statusUpdateReject', @cardActionCategoryId, 'card.application.statusUpdateReject', '{}')
    ,('card.application.statusUpdateDecline', @cardActionCategoryId, 'card.application.statusUpdateDecline', '{}')
    ,('card.batch.addNoNameBatch', @cardActionCategoryId, 'card.batch.addNoNameBatch', '{}')
    ,('card.batch.download', @cardActionCategoryId, 'card.batch.download', '{}')
    ,('card.batch.downloadCustom', @cardActionCategoryId, 'card.batch.downloadCustom', '{}')
    ,('card.batch.fetch', @cardActionCategoryId, 'card.batch.fetch', '{}')
    ,('card.batch.get', @cardActionCategoryId, 'card.batch.get', '{}')
    ,('card.batch.list', @cardActionCategoryId, 'card.batch.list', '{}')
    ,('card.batch.statusUpdate', @cardActionCategoryId, 'card.batch.statusUpdate', '{}')
    ,('card.batch.statusUpdateApprove', @cardActionCategoryId, 'card.batch.statusUpdateApprove', '{}')
    ,('card.batch.statusUpdateCompleted', @cardActionCategoryId, 'card.batch.statusUpdateCompleted', '{}')
    ,('card.batch.statusUpdateDecline', @cardActionCategoryId, 'card.batch.statusUpdateDecline', '{}')
    ,('card.batch.statusUpdateEdit', @cardActionCategoryId, 'card.batch.statusUpdateEdit', '{}')
    ,('card.batch.statusUpdateReject', @cardActionCategoryId, 'card.batch.statusUpdateReject', '{}')
    ,('card.batch.statusUpdateSendToProduction', @cardActionCategoryId, 'card.batch.statusUpdateSendToProduction', '{}')
    ,('card.batch.embosserFileGet', @cardActionCategoryId, 'card.batch.embosserFileGet', '{}')
    ,('card.embossedType.fetch', @cardActionCategoryId, 'card.embossedType.fetch', '{}')
    ,('card.ownershipType.fetch', @cardActionCategoryId, 'card.ownershipType.fetch', '{}')
    ,('card.bin.add', @cardActionCategoryId, 'card.bin.add', '{}')
    ,('card.bin.edit', @cardActionCategoryId, 'card.bin.edit', '{}')
    ,('card.bin.fetch', @cardActionCategoryId, 'card.bin.fetch', '{}')
    ,('card.bin.get', @cardActionCategoryId, 'card.bin.get', '{}')
    ,('card.bin.list', @cardActionCategoryId, 'card.bin.get', '{}')
    ,('card.cardInProduction.fetch', @cardActionCategoryId, 'card.cardInProduction.fetch', '{}')
    ,('card.card.get', @cardActionCategoryId, 'card.card.get', '{}')
    ,('card.cardInProduction.get', @cardActionCategoryId, 'card.cardInProduction.get', '{}')
    ,('card.card.search', @cardActionCategoryId, 'card.card.search', '{}')
    ,('card.card.statusUpdate', @cardActionCategoryId, 'card.card.statusUpdate', '{}')
    ,('card.card.statusUpdateAllocate', @cardActionCategoryId, 'card.card.statusUpdateAllocate', '{}')
    ,('card.card.statusUpdateS', @cardActionCategoryId, 'card.card.statusUpdateS', '{}')
    ,('card.card.statusUpdateApprove', @cardActionCategoryId, 'card.card.statusUpdateApprove', '{}')
    ,('card.card.statusUpdateDestruct', @cardActionCategoryId, 'card.card.statusUpdateDestruct', '{}')
    ,('card.cardInUse.fetch', @cardActionCategoryId, 'card.cardInUse.fetch', '{}')
    ,('card.cardInUse.get', @cardActionCategoryId, 'card.cardInUse.get', '{}')
    ,('card.cardInUse.statusUpdate', @cardActionCategoryId, 'card.cardInUse.statusUpdate', '{}')
    ,('card.cardNumberConstruction.fetch', @cardActionCategoryId, 'card.cardNumberConstruction.fetch', '{}')
    ,('card.config.fetch', @cardActionCategoryId, 'card.config.fetch', '{}')
    ,('card.customer.search', @cardActionCategoryId, 'card.customer.search', '{}')
    ,('card.customer.searchTSS', @cardActionCategoryId, 'card.customer.searchTSS', '{}')
    ,('card.customerType.list', @cardActionCategoryId, 'card.customerType.list', '{}')
    ,('card.noNameApplication.add', @cardActionCategoryId, 'card.noNameApplication.add', '{}')
    ,('card.issueType.fetch', @cardActionCategoryId, 'card.issueType.fetch', '{}')
    ,('card.moduleAction.list', @cardActionCategoryId, 'card.moduleAction.list', '{}')
    ,('card.periodicCardFee.fetch', @cardActionCategoryId, 'card.periodicCardFee.fetch', '{}')
    ,('card.person.search', @cardActionCategoryId, 'card.person.search', '{}')
    ,('card.person.searchTSS', @cardActionCategoryId, 'card.person.searchTSS', '{}')
    ,('card.product.add', @cardActionCategoryId, 'card.product.add', '{}')
    ,('card.product.edit', @cardActionCategoryId, 'card.product.edit', '{}')
    ,('card.product.fetch', @cardActionCategoryId, 'card.product.fetch', '{}')
    ,('card.product.get', @cardActionCategoryId, 'card.product.get', '{}')
    ,('card.product.list', @cardActionCategoryId, 'card.product.list', '{}')
    ,('card.reason.statusUpdate', @cardActionCategoryId, 'card.reason.statusUpdate', '{}')
    ,('card.reason.add', @cardActionCategoryId, 'card.reason.add', '{}')
    ,('card.reason.fetch', @cardActionCategoryId, 'card.reason.fetch', '{}')
    ,('card.reason.get', @cardActionCategoryId, 'card.reason.get', '{}')
    ,('card.reason.edit', @cardActionCategoryId, 'card.reason.edit', '{}')
    ,('card.reason.list', @cardActionCategoryId, 'card.reason.list', '{}')
    ,('user.configuration.get', @cardActionCategoryId, 'user.configuration.get', '{}')
    ,('card.reason.delete', @cardActionCategoryId, 'card.reason.delete', '{}')
    ,('card.statusAction.fetch', @cardActionCategoryId, 'card.statusAction.fetch', '{}')
    ,('card.brand.fetch', @cardActionCategoryId, 'card.brand.fetch', '{}')
    ,('card.card.statusUpdateApproveAcceptance', @cardActionCategoryId, 'card.card.statusUpdateApproveAcceptance', '{}')
    ,('card.card.statusUpdateAllocateAndChangeBranch', @cardActionCategoryId, 'card.card.statusUpdateAllocateAndChangeBranch', '{}')
    ,('card.cardInUse.statusUpdateEdit', @cardActionCategoryId, 'card.cardInUse.statusUpdateEdit', '{}')
    ,('card.cardInUse.statusUpdateRejectActivation', @cardActionCategoryId, 'card.cardInUse.statusUpdateRejectActivation', '{}')
    ,('card.cardInUse.statusUpdateHOT', @cardActionCategoryId, 'card.cardInUse.statusUpdateHOT', '{}')
    ,('card.cardInUse.statusUpdateApproveActivate', @cardActionCategoryId, 'card.cardInUse.statusUpdateApproveActivate', '{}')
    ,('card.cardInUse.statusUpdateDeactivate', @cardActionCategoryId, 'card.cardInUse.statusUpdateDeactivate', '{}')
    ,('card.card.statusUpdateReject', @cardActionCategoryId, 'card.card.statusUpdateReject', '{}')
    ,('card.cardInUse.statusUpdateApproveDestruction', @cardActionCategoryId, 'card.cardInUse.statusUpdateApproveDestruction', '{}')
    ,('card.cardInUse.statusUpdateApproveDeactivation', @cardActionCategoryId, 'card.cardInUse.statusUpdateApproveDeactivation', '{}')
    ,('card.cardInUse.statusUpdateRejectDeactivation', @cardActionCategoryId, 'card.cardInUse.statusUpdateRejectDeactivation', '{}')
    ,('card.batch.generatePinMail', @cardActionCategoryId, 'card.batch.generatePinMail', '{}')
    ,('card.card.statusUpdateAcceptSentCards', @cardActionCategoryId, 'card.card.statusUpdateAcceptSentCards', '{}')
    ,('card.card.statusUpdateAcceptDeclinedCards', @cardActionCategoryId, 'card.card.statusUpdateAcceptDeclinedCards', '{}')
    ,('card.card.statusUpdateAcceptRejectedCards', @cardActionCategoryId, 'card.card.statusUpdateAcceptRejectedCards', '{}')
    ,('card.card.statusUpdateAllocateRejectedCards', @cardActionCategoryId, 'card.card.statusUpdateAllocateRejectedCards', '{}')
    ,('card.card.statusUpdateDeclineFromAccepted', @cardActionCategoryId, 'card.card.statusUpdateDeclineFromAccepted', '{}')
    ,('card.card.statusUpdateDeclineFromRejectedAllocation', @cardActionCategoryId, 'card.card.statusUpdateDeclineFromRejectedAllocation', '{}')
    ,('card.card.statusUpdateDeclineFromRejectedAcceptance', @cardActionCategoryId, 'card.card.statusUpdateDeclineFromRejectedAcceptance', '{}')
    ,('card.card.statusUpdateApproveDestruction', @cardActionCategoryId, 'card.card.statusUpdateApproveDestruction', '{}')
    ,('card.card.statusUpdateRejectAllocation', @cardActionCategoryId, 'card.card.statusUpdateRejectAllocation', '{}')
    ,('card.card.statusUpdateRejectAcceptance', @cardActionCategoryId, 'card.card.statusUpdateRejectAcceptance', '{}')
    ,('card.card.statusUpdateRejectSentCards', @cardActionCategoryId, 'card.card.statusUpdateRejectSentCards', '{}')
    ,('card.cardInUse.resetPINRetries', @cardActionCategoryId, 'card.cardInUse.resetPINRetries', '{}')
    ,('card.cardInUse.statusUpdateDestructFromAccepted', @cardActionCategoryId, 'card.cardInUse.statusUpdateDestructFromAccepted', '{}')
    ,('card.cardInUse.statusUpdateDestructFromInactive', @cardActionCategoryId, 'card.cardInUse.statusUpdateDestructFromInactive', '{}')
    ,('card.cardInUse.statusUpdateDestructFromHot', @cardActionCategoryId, 'card.cardInUse.statusUpdateDestructFromHot', '{}')
    ,('card.cardInUse.statusUpdateDestructFromBlocked', @cardActionCategoryId, 'card.cardInUse.statusUpdateDestructFromBlocked', '{}')
    ,('card.cardInUse.statusUpdateActivate', @cardActionCategoryId, 'card.cardInUse.statusUpdateActivate', '{}')
    ,('card.card.statusUpdateDeclineFromPingDestruction', @cardActionCategoryId, 'card.card.statusUpdateDeclineFromPingDestruction', '{}')
    ,('card.cardInUse.statusUpdateRejectDestruction', @cardActionCategoryId, 'card.cardInUse.statusUpdateRejectDestruction', '{}')
    ,('card.card.statusUpdateSend', @cardActionCategoryId, 'card.card.statusUpdateSend', '{}')
    ,('card.card.statusUpdateDeclineFromPendingDestruction', @cardActionCategoryId, 'card.card.statusUpdateDeclineFromPendingDestruction', '{}')
    ,('card.product.statusUpdate', @cardActionCategoryId, 'card.product.statusUpdate', '{}')
    ,('card.type.add', @cardActionCategoryId, 'card.type.add', '{}')
    ,('card.type.edit', @cardActionCategoryId, 'card.type.edit', '{}')
    ,('card.type.fetch', @cardActionCategoryId, 'card.type.fetch', '{}')
    ,('card.type.get', @cardActionCategoryId, 'card.type.get', '{}')
    ,('card.emvTags.list', @cardActionCategoryId, 'card.emvTags.list', '{}')
    ,('card.cdol1Profile.list', @cardActionCategoryId, 'card.cdol1Profile.list', '{}')
    ,('card.type.list', @cardActionCategoryId, 'card.type.list', '{}')
     ,('card.batch.checkDownload', @cardActionCategoryId, 'card.batch.checkDownload', '{}')
     ,('card.documentType.list', @cardActionCategoryId, 'card.documentType.list', '{}')
     ,('card.documentCard.add', @cardActionCategoryId, 'card.documentCard.add', '{}')
     ,('card.documentCard.edit', @cardActionCategoryId, 'card.documentCard.edit', '{}')
     ,('card.documentCard.get', @cardActionCategoryId, 'card.documentCard.get', '{}')
     ,('card.documentApplication.add', @cardActionCategoryId, 'card.documentApplication.add', '{}')
     ,('card.documentApplication.edit', @cardActionCategoryId, 'card.documentApplication.edit', '{}')
     ,('card.documentApplication.get', @cardActionCategoryId, 'card.documentApplication.get', '{}')
     ,('card.documentApplication.delete', @cardActionCategoryId, 'card.documentApplication.delete', '{}')
     ,('pan.number.generate', @cardActionCategoryId, 'pan.number.generate', '{}')
     ,('card.generated.add', @cardActionCategoryId, 'card.generated.add', '{}')
     ,('card.report.listOfCards', @cardActionCategoryId, 'card.report.listOfCards', '{}')
     ,('card.report.export', @cardActionCategoryId, 'card.report.export', '{}')
     ,('card.report.transfer', @cardActionCategoryId, 'card.report.transfer', '{}')
     ,('card.batch.check', @cardActionCategoryId, 'card.batch.check', '{}')
	 ,('card.status.list', @cardActionCategoryId, 'card.status.list', '{}')
     ,('card.cipher.list', @cardActionCategoryId, 'card.cipher.list', '{}')
     ,('card.batch.pansGet', @cardActionCategoryId, 'card.cipher.list', '{}')
     ,('card.card.panGet', @cardActionCategoryId, 'card.card.panGet', '{}')

;MERGE into [user].[action] as dd
using
(
    select [actionId], [actionCategoryId], [description], [valueMap]
    from @action
) d on dd.actionId=d.actionId

WHEN NOT MATCHED BY TARGET THEN
    INSERT ([actionId], [actionCategoryId], [description], [valueMap])
    VALUES ([actionId], [actionCategoryId], [description], [valueMap]);


