export const TOGGLE_CREATE_DIALOG = Symbol('TOGGLE_CREATE_DIALOG');
export const FETCH_BUSINESS_UNITS = Symbol('FETCH_BUSINESS_UNITS');
export const FETCH_DOCUMENT_TYPES = Symbol('FETCH_DOCUMENT_TYPES');
export const FETCH_CARD_PRODUCTS = Symbol('FETCH_CARD_PRODUCTS');
export const FETCH_CARD_TYPES = Symbol('FETCH_CARD_TYPES');
export const CREATE_APPLICATION = Symbol('CREATE_APPLICATION');

export const SEARCH_CARD_NUMBER = Symbol('SEARCH_CARD_NUMBER');

export const SEARCH_CUSTOMER_BY_NAME = Symbol('SEARCH_CUSTOMER_BY_NAME');
export const CLOSE_CUSTOMERS_POPUP = Symbol('CLOSE_CUSTOMERS_POPUP');
export const CHOOSE_CUSTOMER_FROM_LIST = Symbol('CHOOSE_CUSTOMER_FROM_LIST');

export const SEARCH_PERSON_BY_NUMBER = Symbol('SEARCH_PERSON_BY_NUMBER');
export const CLOSE_PERSONS_POPUP = Symbol('CLOSE_PERSONS_POPUP');
export const CHOOSE_PERSON_FROM_LIST = Symbol('CHOOSE_PERSON_FROM_LIST');

// accounts
export const FETCH_ACCOUNTS = Symbol('FETCH_ACCOUNTS');

export const CHANGE_BUSINESS_UNIT = Symbol('CHANGE_BUSINESS_UNIT');
export const CHANGE_ISSUING_BUSINESS_UNIT = Symbol('CHANGE_ISSUING_BUSINESS_UNIT');
export const CHANGE_FILE = Symbol('CHANGE_FILE');
export const CHANGE_CARD_PRODUCT = Symbol('CHANGE_CARD_PRODUCT');
export const CHANGE_CARD_TYPE = Symbol('CHANGE_CARD_TYPE');
export const CHANGE_CARDHOLDER_NAME = Symbol('CHANGE_CARDHOLDER_NAME');
export const CHANGE_MAKER_COMMENT = Symbol('CHANGE_MAKER_COMMENT');
export const SET_ERRORS = Symbol('SET_ERRORS');
