export const EDIT_PRODUCT = Symbol('EDIT_PRODUCT');
export const CHANGE_EDIT_ITEM_FIELD = Symbol('CHANGE_EDIT_ITEM_FIELD');
export const FETCH_ACCOUNT_TYPES = Symbol('FETCH_ACCOUNT_TYPES');
export const FETCH_CARD_PRODUCT_BY_ID = Symbol('FETCH_CARD_PRODUCT_BY_ID');
export const REMOVE_CARD_PRODUCT = Symbol('REMOVE_CARD_PRODUCT');
export const OPEN_CONFIRMATION = Symbol('OPEN_CONFIRMATION');
export const CLOSE_CONFIRMATION = Symbol('CLOSE_CONFIRMATION');
