export const OPEN_DETAILS_DIALOG = Symbol('OPEN_DETAILS_DIALOG');
export const CLOSE_DETAILS_DIALOG = Symbol('CLOSE_DETAILS_DIALOG');
export const FETCH_APPLICATION_DETAILS = Symbol('FETCH_APPLICATION_DETAILS');

export const FETCH_BUSINESS_UNITS = Symbol('FETCH_BUSINESS_UNITS');
export const FETCH_CARD_PRODUCTS = Symbol('FETCH_CARD_PRODUCTS');

export const CHANGE_DROPDOWN = Symbol('CHANGE_DROPDOWN');
export const CHANGE_CARDHOLDER_NAME = Symbol('CHANGE_CARDHOLDER_NAME');
export const CHANGE_MAKER_COMMENT = Symbol('CHANGE_MAKER_COMMENT');
export const SET_ERRORS = Symbol('SET_ERRORS');
export const FETCH_DOCUMENT_TYPES = Symbol('FETCH_DOCUMENT_TYPES');
