ALTER VIEW [integration].[vAccount] --view that shows information about all customer accounts
AS
SELECT
    '1' as customerNumber,
    7 as accountTypeId,
    'account Type 7' as accountTypeName,
    'USD' as currency,
    1000 as availableBalance,
    2000 as ledgerBalance,
    '000001'  collate database_default as accountNumber,
    'Any one' as methodOfOperationId,
    'current' atmType,
    '' countryId,
    '' regionId,
    '' cityId,
    '' organizationId,
    '' supervisorId,
    '' ownerId,
    '' accountProductId,
    '' cardProductId,
    '' accountId,
    '' accountAlias,
	'' linkedAccount,
	'' accountCheckAmount,
	'' accountCheckMask,
	'' productCheckAmount,
	'' productCheckMask

UNION ALL

SELECT
    '1' as customerNumber,
    8 as accountTypeId,
    'account Type 8' as accountTypeName,
    'USD' as currency,
    1000 as availableBalance,
    2000 as ledgerBalance,
    '000002'  collate database_default as accountNumber,
    'Any one' as methodOfOperationId,
    'current' atmType,
    '' countryId,
    '' regionId,
    '' cityId,
    '' organizationId,
    '' supervisorId,
    '' ownerId,
    '' accountProductId,
    '' cardProductId,
    '' accountId,
    '' accountAlias,
	'' linkedAccount,
	'' accountCheckAmount,
	'' accountCheckMask,
	'' productCheckAmount,
	'' productCheckMask

UNION ALL

SELECT
    '1' as customerNumber,
    3 as accountTypeId,
    'account Type 3' as accountTypeName,
    'USD' as currency,
    1000 as availableBalance,
    2000 as ledgerBalance,
    '000003'  collate database_default as accountNumber,
    'Any one' as methodOfOperationId,
    'current' atmType,
    '' countryId,
    '' regionId,
    '' cityId,
    '' organizationId,
    '' supervisorId,
    '' ownerId,
    '' accountProductId,
    '' cardProductId,
    '' accountId,
    '' accountAlias,
	'' linkedAccount,
	'' accountCheckAmount,
	'' accountCheckMask,
	'' productCheckAmount,
	'' productCheckMask

UNION ALL

SELECT
    '2' as customerNumber,
    4 as accountTypeId,
    'account Type 4' as accountTypeName,
    'USD' as currency,
    1000 as availableBalance,
    2000 as ledgerBalance,
    '000004'  collate database_default as accountNumber,
    'Any one' as methodOfOperationId,
    'current' atmType,
    '' countryId,
    '' regionId,
    '' cityId,
    '' organizationId,
    '' supervisorId,
    '' ownerId,
    '' accountProductId,
    '' cardProductId,
    '' accountId,
    '' accountAlias,
	'' linkedAccount,
	'' accountCheckAmount,
	'' accountCheckMask,
	'' productCheckAmount,
	'' productCheckMask

UNION ALL

SELECT
    '2' as customerNumber,
    5 as accountTypeId,
    'account Type 5' as accountTypeName,
    'USD' as currency,
    1000 as availableBalance,
    2000 as ledgerBalance,
    '000005'  collate database_default as accountNumber,
    'Any one' as methodOfOperationId,
    'current' atmType,
    '' countryId,
    '' regionId,
    '' cityId,
    '' organizationId,
    '' supervisorId,
    '' ownerId,
    '' accountProductId,
    '' cardProductId,
    '' accountId,
    '' accountAlias,
	'' linkedAccount,
	'' accountCheckAmount,
	'' accountCheckMask,
	'' productCheckAmount,
	'' productCheckMask

UNION ALL

SELECT
    '3' as customerNumber,
    6 as accountTypeId,
    'account Type 6' as accountTypeName,
    'USD' as currency,
    1000 as availableBalance,
    2000 as ledgerBalance,
    '000006'  collate database_default as accountNumber,
    'Any one' as methodOfOperationId,
    'current' atmType,
    '' countryId,
    '' regionId,
    '' cityId,
    '' organizationId,
    '' supervisorId,
    '' ownerId,
    '' accountProductId,
    '' cardProductId,
    '' accountId,
    '' accountAlias,
	'' linkedAccount,
	'' accountCheckAmount,
	'' accountCheckMask,
	'' productCheckAmount,
	'' productCheckMask

UNION ALL

SELECT
    '4' as customerNumber,
    7 as accountTypeId,
    'account Type 7' as accountTypeName,
    'USD' as currency,
    1000 as availableBalance,
    2000 as ledgerBalance,
    '000007'  collate database_default as accountNumber,
    'Any one' as methodOfOperationId,
    'current' atmType,
    '' countryId,
    '' regionId,
    '' cityId,
    '' organizationId,
    '' supervisorId,
    '' ownerId,
    '' accountProductId,
    '' cardProductId,
    '' accountId,
    '' accountAlias,
	'' linkedAccount,
	'' accountCheckAmount,
	'' accountCheckMask,
	'' productCheckAmount,
	'' productCheckMask

UNION ALL

SELECT
    '5' as customerNumber,
    7 as accountTypeId,
    'account Type 7' as accountTypeName,
    'USD' as currency,
    1000 as availableBalance,
    2000 as ledgerBalance,
    '000008'  collate database_default as accountNumber,
    'Any one' as methodOfOperationId,
    'current' atmType,
    '' countryId,
    '' regionId,
    '' cityId,
    '' organizationId,
    '' supervisorId,
    '' ownerId,
    '' accountProductId,
    '' cardProductId,
    '' accountId,
    '' accountAlias,
	'' linkedAccount,
	'' accountCheckAmount,
	'' accountCheckMask,
	'' productCheckAmount,
	'' productCheckMask

UNION ALL

SELECT
    '5' as customerNumber,
    5 as accountTypeId,
    'account Type 5' as accountTypeName,
    'USD' as currency,
    1000 as availableBalance,
    2000 as ledgerBalance,
    '000009'  collate database_default as accountNumber,
    'Any one' as methodOfOperationId,
    'current' atmType,
    '' countryId,
    '' regionId,
    '' cityId,
    '' organizationId,
    '' supervisorId,
    '' ownerId,
    '' accountProductId,
    '' cardProductId,
    '' accountId,
    '' accountAlias,
	'' linkedAccount,
	'' accountCheckAmount,
	'' accountCheckMask,
	'' productCheckAmount,
	'' productCheckMask

UNION ALL

SELECT
    '6' as customerNumber,
    7 as accountTypeId,
    'account Type 7' as accountTypeName,
    'USD' as currency,
    1000 as availableBalance,
    2000 as ledgerBalance,
    '0000010'  collate database_default as accountNumber,
    'Any one' as methodOfOperationId,
    'current' atmType,
    '' countryId,
    '' regionId,
    '' cityId,
    '' organizationId,
    '' supervisorId,
    '' ownerId,
    '' accountProductId,
    '' cardProductId,
    '' accountId,
    '' accountAlias,
	'' linkedAccount,
	'' accountCheckAmount,
	'' accountCheckMask,
	'' productCheckAmount,
	'' productCheckMask

UNION ALL

SELECT
    '7' as customerNumber,
    3 as accountTypeId,
    'account Type 3' as accountTypeName,
    'USD' as currency,
    1000 as availableBalance,
    2000 as ledgerBalance,
    '0000011'  collate database_default as accountNumber,
    'Any one' as methodOfOperationId,
    'current' atmType,
    '' countryId,
    '' regionId,
    '' cityId,
    '' organizationId,
    '' supervisorId,
    '' ownerId,
    '' accountProductId,
    '' cardProductId,
    '' accountId,
    '' accountAlias,
	'' linkedAccount,
	'' accountCheckAmount,
	'' accountCheckMask,
	'' productCheckAmount,
	'' productCheckMask

UNION ALL

SELECT
    '8' as customerNumber,
    8 as accountTypeId,
    'account Type 7' as accountTypeName,
    'USD' as currency,
    1000 as availableBalance,
    2000 as ledgerBalance,
    '0000012'  collate database_default as accountNumber,
    'Any one' as methodOfOperationId,
    'current' atmType,
    '' countryId,
    '' regionId,
    '' cityId,
    '' organizationId,
    '' supervisorId,
    '' ownerId,
    '' accountProductId,
    '' cardProductId,
    '' accountId,
    '' accountAlias,
	'' linkedAccount,
	'' accountCheckAmount,
	'' accountCheckMask,
	'' productCheckAmount,
	'' productCheckMask

UNION ALL

SELECT
    '8' as customerNumber,
    3 as accountTypeId,
    'account Type 3' as accountTypeName,
    'USD' as currency,
    1000 as availableBalance,
    2000 as ledgerBalance,
    '0000013'  collate database_default as accountNumber,
    'Any one' as methodOfOperationId,
    'current' atmType,
    '' countryId,
    '' regionId,
    '' cityId,
    '' organizationId,
    '' supervisorId,
    '' ownerId,
    '' accountProductId,
    '' cardProductId,
    '' accountId,
    '' accountAlias,
	'' linkedAccount,
	'' accountCheckAmount,
	'' accountCheckMask,
	'' productCheckAmount,
	'' productCheckMask

UNION ALL

SELECT
    '7' as customerNumber,
    7 as accountTypeId,
    'account Type 7' as accountTypeName,
    'USD' as currency,
    1000 as availableBalance,
    2000 as ledgerBalance,
    '0000014'  collate database_default as accountNumber,
    'Any one' as methodOfOperationId,
    'current' atmType,
    '' countryId,
    '' regionId,
    '' cityId,
    '' organizationId,
    '' supervisorId,
    '' ownerId,
    '' accountProductId,
    '' cardProductId,
    '' accountId,
    '' accountAlias,
	'' linkedAccount,
	'' accountCheckAmount,
	'' accountCheckMask,
	'' productCheckAmount,
	'' productCheckMask

UNION ALL

SELECT
    '6' as customerNumber,
    8 as accountTypeId,
    'account Type 8' as accountTypeName,
    'USD' as currency,
    1000 as availableBalance,
    2000 as ledgerBalance,
    '0000015'  collate database_default as accountNumber,
    'Any one' as methodOfOperationId,
    'current' atmType,
    '' countryId,
    '' regionId,
    '' cityId,
    '' organizationId,
    '' supervisorId,
    '' ownerId,
    '' accountProductId,
    '' cardProductId,
    '' accountId,
    '' accountAlias,
	'' linkedAccount,
	'' accountCheckAmount,
	'' accountCheckMask,
	'' productCheckAmount,
	'' productCheckMask

UNION ALL

SELECT
    '5' as customerNumber,
    8 as accountTypeId,
    'account Type 8' as accountTypeName,
    'USD' as currency,
    1000 as availableBalance,
    2000 as ledgerBalance,
    '0000016'  collate database_default as accountNumber,
    'Any one' as methodOfOperationId,
    'current' atmType,
    '' countryId,
    '' regionId,
    '' cityId,
    '' organizationId,
    '' supervisorId,
    '' ownerId,
    '' accountProductId,
    '' cardProductId,
    '' accountId,
    '' accountAlias,
	'' linkedAccount,
	'' accountCheckAmount,
	'' accountCheckMask,
	'' productCheckAmount,
	'' productCheckMask

UNION ALL

SELECT
    c.customerNumber,
    npt.itemNameId as accountTypeId,
    npt.itemName as description,
    itn.itemName,
    isnull ((b.credit - b.debit),0) AS balance,
    isnull ((b.credit - b.debit),0) AS balance,
    a.accountNumber,
    '' as methodOfOperationId,
    'current' atmType,
    '' countryId,
    '' regionId,
    '' cityId,
    '' organizationId,
    '' supervisorId,
    ownerId,
    p.itemNameId as accountProductId,
    '' cardProductId,
    a.accountId,
    '' accountAlias,
	linkedAccount,
	a.checkAmount as accountCheckAmount,
	a.checkMask accountCheckMask,
	p.checkAmount as productCheckAmount,
	p.checkMask as productCheckMask
FROM customer.customer c
JOIN ledger.account a on a.ownerId = c.actorId
JOIN ledger.product p ON p.productId = a.productId
JOIN core.itemName npt ON npt.itemNameId = p.productTypeId
JOIN core.itemName ng ON ng.itemNameId = npt.parentItemNameId
JOIN ledger.productGroup pg ON pg.productGroupId = ng.itemNameId
JOIN core.currency cc ON cc.currencyId = p.currencyId 
JOIN core.itemName itn on itn.itemNameId = cc.itemNameId
LEFT JOIN ledger.balance b ON b.accountId = a.accountId