export const FETCH_OWNERSHIP_TYPES = Symbol('FETCH_OWNERSHIP_TYPES');
export const FETCH_PERIODIC_CARD_FEES = Symbol('FETCH_PERIODIC_CARD_FEES');
export const FETCH_CARD_FEES = Symbol('FETCH_CARD_FEES');
export const FETCH_BUSINESS_UNITS = Symbol('FETCH_BUSINESS_UNITS');
export const FETCH_CUSTOMER_TYPES = Symbol('FETCH_CUSTOMER_TYPES');
export const FETCH_ACCOUNT_TYPES = Symbol('FETCH_CUSTOMER_TYPES');
export const CREATE_PRODUCT = Symbol('CREATE_PRODUCT');
export const TOGGLE_CREATE_CARD_PRODUCT_POPUP = Symbol('TOGGLE_CREATE_CARD_PRODUCT_POPUP');
