CREATE TABLE [atm].[terminal](
    actorId bigint NOT NULL,
    luno varchar(9),
    tmk varchar(33),
    tmkkvv varchar(6),
    [name] varchar(50) NOT NULL,
    [address] varchar(40) NOT NULL,
    [city] varchar(13) NULL,
    [state] varchar(2) NULL,
    [country] varchar(2) NULL,
    customization nvarchar(50),
    institutionCode varchar(11),
    terminalId varchar(8) NOT NULL,
    identificationCode varchar(15),
    merchantId varchar(50),
    merchantType varchar(4),
    tsn int,
    cassette1Currency varchar(3) NULL,
    cassette1Denomination int NULL,
    cassette2Currency varchar(3) NULL,
    cassette2Denomination int NULL,
    cassette3Currency varchar(3) NULL,
    cassette3Denomination int NULL,
    cassette4Currency varchar(3) NULL,
    cassette4Denomination int NULL,
    tillAccount varchar(50),
    feeAccount varchar(50),
    commissionAccount varchar(50),
    [offline] bit NULL,
    branchId bigint NULL,
    CONSTRAINT pkAtmTerminal PRIMARY KEY CLUSTERED (actorId ASC),
    CONSTRAINT fkAtmTerminal_Actor FOREIGN KEY(actorId) REFERENCES [core].[actor] (actorId),
    CONSTRAINT fkAtmTerminal_Branch FOREIGN KEY(branchId) REFERENCES [customer].[organization] (actorId),
    CONSTRAINT ukAtmTerminal_TerminalIdUnique UNIQUE(terminalId),
    CONSTRAINT ukAtmTerminal_TmkkvvUnique UNIQUE(tmkkvv)
    
)
