CREATE TABLE [atm].[fitness](
    atmId bigint NOT NULL,
    clock varchar(10),
    comms varchar(10),
    [disk] varchar(10),
    cardReader varchar(10),
    cashHandler varchar(10),
    depository varchar(10),
    receiptPrinter varchar(10),
    journalPrinter varchar(10),
    nightDepository varchar(10),
    encryptor varchar(10),
    camera varchar(10),
    doorAccess varchar(10),
    flexDisk varchar(10),
    cassette1 varchar(10),
    cassette2 varchar(10),
    cassette3 varchar(10),
    cassette4 varchar(10),
    statementPrinter varchar(10),
    signageDisplay varchar(10),
    systemDisplay varchar(10),
    mediaEntry varchar(10),
    envelopeDispenser varchar(10),
    documentProcessing varchar(10),
    coinDispenser varchar(10),
    voiceGuidance varchar(10),
    noteAcceptor varchar(10),
    chequeProcessor varchar(10),
    CONSTRAINT pkAtmFitness PRIMARY KEY CLUSTERED (atmId ASC),
    CONSTRAINT fkAtmFitness_Terminal FOREIGN KEY(atmId) REFERENCES [atm].[terminal] (actorId)
)