CREATE TABLE [atm].[supplyCounters](
    atmId bigint NOT NULL,
	notes1 int,
	notes2 int,
	notes3 int,
	notes4 int,
	rejected1 int,
	rejected2 int,
	rejected3 int,
	rejected4 int,
	dispensed1 int,
	dispensed2 int,
	dispensed3 int,
	dispensed4 int,
	last1 int,
	last2 int,
	last3 int,
	last4 int,
	captured int,
	transactionCount int,
	transactionSerialNumber int,
    CONSTRAINT pkAtmSupplyCounters PRIMARY KEY CLUSTERED (atmId ASC),
    CONSTRAINT fkAtmSupplyCounters_Terminal FOREIGN KEY(atmId) REFERENCES [atm].[terminal] (actorId)
)