export const OPEN_CREATE_BATCH_DIALOG = Symbol('OPEN_CREATE_BATCH_DIALOG');
export const FETCH_BUSINESS_UNITS = Symbol('FETCH_BUSINESS_UNITS');
export const CLOSE_CREATE_BATCH_DIALOG = Symbol('CLOSE_CREATE_BATCH_DIALOG');
export const CHANGE_BATCH_NAME = Symbol('CHANGE_BATCH_NAME');
export const CHANGE_BUSINESS_UNIT = Symbol('CHANGE_BUSINESS_UNIT');
export const UNCHECK_APPLICATION = Symbol('UNCHECK_APPLICATION');
export const CHECK_APPLICATION = Symbol('CHECK_APPLICATION');
export const SET_ERRORS = Symbol('SET_ERRORS');
