export const OPEN_ADD_TO_EXISTING_BATCH_DIALOG = Symbol('OPEN_ADD_TO_EXISTING_BATCH_DIALOG');
export const CLOSE_ADD_TO_EXISTING_BATCH_DIALOG = Symbol('CLOSE_ADD_TO_EXISTING_BATCH_DIALOG');
export const FETCH_BATCHES = Symbol('FETCH_BATCHES');
export const CHANGE_BATCH = Symbol('CHANGE_BATCH');
export const CHECK_APPLICATION = Symbol('CHECK_APPLICATION');
export const SET_ERRORS = Symbol('SET_ERRORS');
